workflows:
  ios-diagnostic:
    name: iOS Diagnostic Build
    instance_type: mac_mini_m1
    max_build_duration: 120
    environment:
      node: latest
      xcode: latest
      cocoapods: default
    scripts:
      - name: Project Diagnostics
        script: |
          echo "===== ENVIRONMENT INFO ====="
          node -v
          npm -v
          xcodebuild -version
          pod --version
          
          echo "===== PROJECT STRUCTURE ====="
          ls -la
          
          echo "===== PACKAGE.JSON ====="
          cat package.json
          
          echo "===== CHECK IOS DIRECTORY ====="
          if [ -d "ios" ]; then
            echo "iOS directory exists:"
            ls -la ios/
          else
            echo "iOS directory does not exist, creating it"
            npx react-native init temp_project --template react-native-template-typescript
            cp -R temp_project/ios ./ios
            rm -rf temp_project
            echo "Created iOS directory:"
            ls -la ios/
          fi
      
      - name: Android Alternative
        script: |
          echo "===== CHECKING ANDROID SETUP ====="
          if [ -d "android" ]; then
            echo "Android directory exists:"
            ls -la android/
            echo "We could build for Android instead as a faster alternative"
          fi