workflows:
  android-workflow:
    name: Android Build
    instance_type: linux
    max_build_duration: 120
    environment:
      node: latest
      java: 11
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Build Android
        script: |
          cd android
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/**/*.apk

  web-workflow:
    name: Web Build
    instance_type: linux
    max_build_duration: 120
    environment:
      node: latest
    scripts:
      - name: Install dependencies
        script: |
          npm install
          npm install --save react-native-web react-dom
          npm install --save-dev webpack webpack-cli webpack-dev-server babel-loader html-webpack-plugin @babel/core @babel/preset-env @babel/preset-react
      - name: Create webpack config
        script: |
          cat > webpack.config.js << 'EOL'
          const path = require('path');
          const HtmlWebpackPlugin = require('html-webpack-plugin');

          module.exports = {
            entry: './index.js',
            output: {
              path: path.join(__dirname, 'dist'),
              filename: 'bundle.js',
            },
            module: {
              rules: [
                {
                  test: /\.(js|jsx)$/,
                  exclude: /node_modules/,
                  use: {
                    loader: 'babel-loader',
                    options: {
                      presets: ['@babel/preset-env', '@babel/preset-react'],
                    },
                  },
                },
              ],
            },
            resolve: {
              alias: {
                'react-native$': 'react-native-web',
              },
              extensions: ['.web.js', '.js'],
            },
            plugins: [
              new HtmlWebpackPlugin({
                template: './public/index.html',
              }),
            ],
          };
          EOL
      - name: Create HTML template
        script: |
          mkdir -p public
          cat > public/index.html << 'EOL'
          <!DOCTYPE html>
          <html>
            <head>
              <meta charset="UTF-8" />
              <meta name="viewport" content="width=device-width, initial-scale=1.0" />
              <title>React Native Web App</title>
              <style>
                html, body, #root { height: 100%; }
              </style>
            </head>
            <body>
              <div id="root"></div>
            </body>
          </html>
          EOL
      - name: Build Web
        script: npx webpack --mode production
    artifacts:
      - dist/**