workflows:
  android-free:
    name: Android Build (Free Plan)
    instance_type: mac_mini  # Use mac_mini em vez de linux ou mac_mini_m1
    max_build_duration: 60
    environment:
      node: latest
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Build Android
        script: |
          cd android
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/**/*.apk