workflows:
  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m1
    max_build_duration: 120
    environment:
      node: latest
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          npm install
      
      - name: Check iOS directory
        script: |
          echo "Checking iOS directory content:"
          if [ -d "ios" ]; then
            ls -la ios/
          else
            echo "iOS directory not found, will create it"
            npx react-native-cli init-ios || npx react-native init-ios || echo "Failed to initialize iOS"
            if [ -d "ios" ]; then
              ls -la ios/
            fi
          fi
      
      - name: Install CocoaPods and check project
        script: |
          cd ios
          echo "Installing CocoaPods..."
          pod install || echo "Pod install failed, trying to generate new Podfile"
          
          # Find project name
          PROJECT_NAME=$(ls -d *.xcodeproj | head -n 1 | sed 's/\.xcodeproj//')
          echo "Project name detected: $PROJECT_NAME"
          
          # Check if workspace exists
          if [ ! -d "$PROJECT_NAME.xcworkspace" ]; then
            echo "Workspace not found, will prepare project"
            pod init
            pod install
          fi
          
          echo "Final iOS directory content:"
          ls -la
      
      - name: Build iOS (Debug)
        script: |
          cd ios
          # Find project name automatically
          PROJECT_NAME=$(ls -d *.xcodeproj | head -n 1 | sed 's/\.xcodeproj//')
          echo "Building project: $PROJECT_NAME"
          
          # Build for simulator (more likely to succeed)
          xcodebuild -workspace "$PROJECT_NAME.xcworkspace" \
            -scheme "$PROJECT_NAME" \
            -configuration Debug \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 14' \
            build
    artifacts:
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - /tmp/xcodebuild_logs/*.log